/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_5 (
    input clk,
    input rst,
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] aluOut
  );
  
  
  
  reg [1:0] sel;
  
  integer i;
  
  wire [16-1:0] M_alu_aluOut;
  wire [1-1:0] M_alu_z;
  wire [1-1:0] M_alu_v;
  wire [1-1:0] M_alu_n;
  reg [16-1:0] M_alu_a;
  reg [16-1:0] M_alu_b;
  reg [6-1:0] M_alu_alufn;
  alu_3 alu (
    .rst(rst),
    .clk(clk),
    .a(M_alu_a),
    .b(M_alu_b),
    .alufn(M_alu_alufn),
    .aluOut(M_alu_aluOut),
    .z(M_alu_z),
    .v(M_alu_v),
    .n(M_alu_n)
  );
  
  always @* begin
    M_alu_a = a;
    M_alu_b = b;
    M_alu_alufn = alufn;
    for (i = 1'h0; i < 5'h10; i = i + 1) begin
      sel[0+0-:1] = a[(i)*1+0-:1];
      sel[1+0-:1] = b[(i)*1+0-:1];
      
      case (sel[0+1-:2])
        2'h0: begin
          aluOut[(i)*1+0-:1] = alufn[0+0-:1];
        end
        2'h1: begin
          aluOut[(i)*1+0-:1] = alufn[1+0-:1];
        end
        2'h2: begin
          aluOut[(i)*1+0-:1] = alufn[2+0-:1];
        end
        2'h3: begin
          aluOut[(i)*1+0-:1] = alufn[3+0-:1];
        end
        default: begin
          aluOut[(i)*1+0-:1] = alufn[0+0-:1];
        end
      endcase
    end
  end
endmodule
