/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_8 (
    input clk,
    input rst,
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] aluOut,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] sum;
  
  always @* begin
    sum = 16'h0000;
    v = 1'h0;
    n = 1'h0;
    
    case (alufn[0+1-:2])
      2'h0: begin
        sum = a + b;
        v = (a[15+0-:1] & b[15+0-:1] & ~sum[15+0-:1]) | (~a[15+0-:1] & ~b[15+0-:1] & sum[15+0-:1]);
      end
      2'h1: begin
        sum = a - b;
        v = (a[15+0-:1] & b[15+0-:1] & ~sum[15+0-:1]) | (~a[15+0-:1] & ~b[15+0-:1] & sum[15+0-:1]);
      end
      2'h2: begin
        sum = a * b;
        v = (a[15+0-:1] & b[15+0-:1] & ~sum[15+0-:1]) | (~a[15+0-:1] & ~b[15+0-:1] & sum[15+0-:1]);
      end
      default: begin
        sum = a + b;
        v = (a[15+0-:1] & b[15+0-:1] & ~sum[15+0-:1]) | (~a[15+0-:1] & ~b[15+0-:1] & sum[15+0-:1]);
      end
    endcase
    aluOut = sum;
    if (sum == 16'h0000) begin
      z = 1'h1;
    end else begin
      z = 1'h0;
    end
    n = sum[15+0-:1];
  end
endmodule
