/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_2 (
    input clk,
    input rst,
    output reg out,
    output reg [15:0] aluOut,
    output reg z,
    output reg v,
    output reg n,
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn
  );
  
  
  
  
  always @* begin
    out = 1'h0;
    z = 1'h1;
    v = 1'h0;
    n = 1'h1;
    aluOut = a + b;
  end
endmodule
