/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_7 (
    input clk,
    input rst,
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] aluOut
  );
  
  
  
  wire [16-1:0] M_adder_aluOut;
  wire [1-1:0] M_adder_z;
  wire [1-1:0] M_adder_v;
  wire [1-1:0] M_adder_n;
  reg [16-1:0] M_adder_a;
  reg [16-1:0] M_adder_b;
  reg [6-1:0] M_adder_alufn;
  adder_4 adder (
    .rst(rst),
    .clk(clk),
    .a(M_adder_a),
    .b(M_adder_b),
    .alufn(M_adder_alufn),
    .aluOut(M_adder_aluOut),
    .z(M_adder_z),
    .v(M_adder_v),
    .n(M_adder_n)
  );
  
  always @* begin
    aluOut = 16'h0000;
    M_adder_a = a;
    M_adder_b = b;
    M_adder_alufn = alufn;
    
    case (alufn[1+1-:2])
      2'h1: begin
        aluOut[0+0-:1] = M_adder_z;
      end
      2'h2: begin
        aluOut[0+0-:1] = M_adder_n ^ M_adder_v;
      end
      2'h3: begin
        aluOut[0+0-:1] = M_adder_z | (M_adder_n ^ M_adder_v);
      end
      default: begin
        aluOut[0+0-:1] = 1'h0;
      end
    endcase
  end
endmodule
