/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_seg_5 (
    input [7:0] char,
    output reg [7:0] segs
  );
  
  
  
  always @* begin
    
    case (char)
      1'h0: begin
        segs = 8'h3f;
      end
      1'h1: begin
        segs = 8'h06;
      end
      2'h2: begin
        segs = 8'h5b;
      end
      2'h3: begin
        segs = 8'h4f;
      end
      3'h4: begin
        segs = 8'h66;
      end
      3'h5: begin
        segs = 8'h6d;
      end
      3'h6: begin
        segs = 8'h7d;
      end
      3'h7: begin
        segs = 8'h07;
      end
      4'h8: begin
        segs = 8'h7f;
      end
      4'h9: begin
        segs = 8'h67;
      end
      7'h43: begin
        segs = 8'h39;
      end
      7'h41: begin
        segs = 8'h77;
      end
      7'h64: begin
        segs = 8'h5e;
      end
      7'h62: begin
        segs = 8'h7c;
      end
      7'h65: begin
        segs = 8'h7b;
      end
      7'h72: begin
        segs = 8'h50;
      end
      7'h78: begin
        segs = 8'h49;
      end
      7'h4c: begin
        segs = 8'h38;
      end
      7'h68: begin
        segs = 8'h74;
      end
      7'h6e: begin
        segs = 8'h54;
      end
      7'h55: begin
        segs = 8'h1c;
      end
      7'h76: begin
        segs = 8'h00;
      end
      7'h6d: begin
        segs = 8'h79;
      end
      7'h75: begin
        segs = 8'h4c;
      end
      7'h6c: begin
        segs = 8'h0c;
      end
      default: begin
        segs = 7'h00;
      end
    endcase
  end
endmodule
