/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_9 (
    input clk,
    input rst,
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] aluOut
  );
  
  
  
  always @* begin
    aluOut = a;
    
    case (alufn[0+1-:2])
      2'h0: begin
        aluOut = a << b;
      end
      2'h1: begin
        aluOut = a >> b;
      end
      2'h3: begin
        aluOut = $signed(a) >>> b;
      end
    endcase
  end
endmodule
